Update `Hashable Term` instance so `alphaEquiv t1 t2` implies `hash t1 == hash t2`
GaloisInc/saw-script pull request #1869
Opened 2023-05-16 16:06 UTC by m-yac

The `Hashable` instance requires that if two elements are equal, then they must have the same hash. I noticed that the current `Hashable` instance for `Term` did not satisfy this in two ways:
1. Variable names: `Lambda "x" t u` would have a different hash than `Lambda "y" t u`, even though they are equal (since equality of `Term`s is `alphaEquiv`)
2. `STApp` vs. `Unshared`: `STApp { stAppTermF = t }` would have a different hash than `Unshared t`, even though they are equal (since, as above, equality of `Term`s is `alphaEquiv`, and `alphaEquiv` does not differentiate between the two constructors if they have equal `TermF` representations)

This PR resolves both of these issues: the first by defining a manual `Hashable (TermF e)` instance, and the second by removing the `combine 0x00000000` and `combine 0x55555555` parts of the `Hashable Term` instance which differentiated the `STApp` and `Unshared` constructors.

I noticed that some of this was already discussed in #1830 – in particular [Andrei left a comment](https://github.com/GaloisInc/saw-script/pull/1830#discussion_r1134733604) with an optimization to `alphaEquiv` that can be made if the first change above was implemented. Since I did the latter, I included that optimization.

2023-05-16 16:46 UTC, RyanGlScott requested changes
Consider adding some unit tests for the properties you are trying to establish in the [`saw-core` test suite](https://github.com/GaloisInc/saw-script/tree/master/saw-core).

2023-05-16 16:46 UTC, RyanGlScott commented on saw-core/src/Verifier/SAW/Term/Functor.hs
> +  hashWithSalt salt (Constant ec _) = salt `hashWithSalt` ec
This deserves a comment explaining why we write this instance in such a peculiar why, including a reference to the `alphaEquiv` function (on which this is based).

2023-05-16 16:46 UTC, RyanGlScott commented on saw-core/src/Verifier/SAW/Term/Functor.hs
> +  hashWithSalt salt = hashWithSalt salt . hash
Similarly, leave some commentary about why this is defined like it is, and reference `alphaEquiv`.

2023-05-16 16:46 UTC, RyanGlScott commented on saw-core/src/Verifier/SAW/Term/Functor.hs
> +         i1 == i2 || (h1 == h2 && termf tf1 tf2)
Please explain here that the `h1 == h2` check is merely an optimization.

2023-05-16 19:22 UTC, m-yac commented
Thanks for the comments @RyanGlScott! I added some more commentary in the places you asked – let me know if you think more would be better, or if I need to clarify something.

I will definitely add some unit tests when I get a chance.

2023-05-16 21:43 UTC, samcowger commented
I've just noticed that `Eq` on `TermF e`s is not implemented in terms of alpha equivalence, it's merely derived. Do you think that's worth changing in this PR, so that equivalence of `Term`s and `TermF e`s is more unified?

2023-05-17 14:21 UTC, eddywestbrook commented
> I've just noticed that `Eq` on `TermF e`s is not implemented in terms of alpha equivalence, it's merely derived. Do you think that's worth changing in this PR, so that equivalence of `Term`s and `TermF e`s is more unified?

Ooh, good catch! Yes, `Eq` on `TermF` should use `alphaEquiv`. It looks like the way `alphaEquiv` is defined in fact defines local equality functions for `TermF` and `FlatTermF`, but doesn't export them as _the_ equality functions for those types. That should be fixed.

Also, 100% yes to @RyanGlScott's suggestion! Please add tests for these properties!

2025-04-11 01:19 UTC, sauclovian-g commented
I'm going to open a separate issue (#2290) for `Eq` on `TermF` because it also needs an `Ord` and that code needs to be written. Which ordinarily I'd probably just do but with #2280 incoming I'd like to get this branch merged first.

2025-04-11 04:56 UTC, sauclovian-g commented
Ok, we have some tests now.

2025-04-11 11:16 UTC, RyanGlScott approved these changes

2025-04-11 11:16 UTC, RyanGlScott commented on saw-core/saw-core.cabal
> +    Tests.Functor
Minor nit pick: alphabetize these modules:

```diff
   other-modules:
     Tests.CacheTests
+    Tests.Functor
     Tests.Parser
     Tests.Rewriter
     Tests.SharedTerm
     Tests.Simulator
-    Tests.Functor
```

2025-04-11 11:16 UTC, RyanGlScott commented on saw-core/tests/src/Tests/Functor.hs
> +-- There are three properties of Term/TermF/FlatTermF that the
```suggestion

-- There are three properties of Term/TermF/FlatTermF that the
```

2025-04-11 11:16 UTC, RyanGlScott commented on saw-core/tests/src/Tests/Functor.hs
> +  let _flop _x = seedTwo one one
`_flop` doesn't appear to be used anywhere. Can this definition be removed?

2025-04-11 18:52 UTC, sauclovian-g commented on saw-core/saw-core.cabal
> +    Tests.Functor
Oops, didn't even notice, just added at the end. Fixed

2025-04-11 18:52 UTC, sauclovian-g commented on saw-core/tests/src/Tests/Functor.hs
> +-- There are three properties of Term/TermF/FlatTermF that the
Fixed

2025-04-11 18:52 UTC, sauclovian-g commented on saw-core/tests/src/Tests/Functor.hs
> +  let _flop _x = seedTwo one one
Yes, that was an experimental leftover that wasn't intended to ever appear in the wild. Removed.

2025-04-11 21:40 UTC, merged