Modify `testResolved` to detect partially-overlapping points-tos.
GaloisInc/saw-script pull request #961
Opened 2020-12-08 14:46 UTC by brianhuffman

Previously `testResolved` would detect a later points-to that pointed
entirely inside the region of an earlier points-to, but would not
detect an overlap if the points-tos were done in the opposite order.

This change makes the points-to comparison symmetric, so overlapping
points-to declarations are detected no matter what order they appear
in a spec.

This fixes one of the remaining known false positives from #938.

2020-12-08 18:32 UTC, brianhuffman commented
As I understand it, the problem that this patch fixes is not a soundness problem; rather, it can prevent a situation where the user proves an override that is actually unusable because it has preconditions that contradict each other.

2020-12-08 19:24 UTC, atomb approved these changes
Yeah, this seems like the right way to do it.

Could there have been an issue in the case where two points-tos in the postcondition overlapped, leading to a contradiction, and causing the simulator to assume false from there on? Of course, that would be an issue in any case where a postcondition was contradictory, which we can easily do with a postcondition `Term`.

2020-12-08 19:36 UTC, brianhuffman commented
If there were two overlapping points-to postconditions, then the initial verification would likely fail (as it would have to prove *both* of the points-to postconditions, which would only be possible if the two were in agreement with each other). So there's no soundness problem in that situation.

Of course you could always use `unsafe_assume_spec` with unprovable postconditions to give you an unsound override; but that was always possible with `unsafe_assume_spec`. At best I guess you could say that the overlapping points-tos could make it easier to produce an unsound spec with `unsafe_assume_spec` that doesn't *look* unsound.

2020-12-08 19:48 UTC, atomb commented
Yeah, and unsafe assumptions are always going to be a problem. Sounds good!

2020-12-09 00:44 UTC, andreistefanescu requested changes
lgtm, but let's merge the memory leak fix before merging any changes that may break existing proofs.

2020-12-09 05:59 UTC, brianhuffman commented
@andreistefanescu: The space leak fix (#964) has been merged. Were there any other additional regression tests or proofs that should be added to CI before this one is ready to go in?

2020-12-10 23:52 UTC, andreistefanescu approved these changes
@brianhuffman #893 should detect regressions in the aws-lc and blast proofs, so merge it if tests pass

2021-01-22 12:29 UTC, merged